"""Create deterministic, rights-cleared Recovery 2E acceptance fixtures.

The images are generated only from fixed gradients and geometric marks. They
contain no third-party material, people, customer content, or ambient random
input. The generated corpus is committed so every runtime uses identical bytes.

    python tools/make_recovery_2e_fixtures.py
    python tools/make_recovery_2e_fixtures.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import struct
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from PIL import Image, ImageChops, ImageCms, ImageDraw, ImageEnhance


@dataclass(frozen=True)
class Fixture:
    name: str
    data: bytes
    description: str


def _canonical_srgb_profile() -> bytes:
    profile = bytearray(ImageCms.ImageCmsProfile(ImageCms.createProfile("sRGB")).tobytes())
    profile[24:36] = b"\x07\xd0\x00\x01\x00\x01\x00\x00\x00\x00\x00\x00"
    profile[84:100] = b"\x00" * 16
    return bytes(profile)


def _fixed(value: float) -> bytes:
    return struct.pack(">i", round(value * 65536))


def _xyz_tag(x: float, y: float, z: float) -> bytes:
    return b"XYZ \x00\x00\x00\x00" + _fixed(x) + _fixed(y) + _fixed(z)


def _text_tag(value: str) -> bytes:
    return b"text\x00\x00\x00\x00" + value.encode("ascii") + b"\x00"


def _cmyk_lut_tag() -> bytes:
    """A tiny deterministic CMYK input LUT profile tag.

    This fixture profile is deliberately not a press characterization. Its only
    role is to give LittleCMS a valid, rights-clear CMYK-to-Lab transform whose
    effect and profile handling can be tested without shipping a vendor profile.
    """

    header = b"mft1\x00\x00\x00\x00" + bytes((4, 3, 2, 0))
    matrix = b"".join(_fixed(value) for value in (1, 0, 0, 0, 1, 0, 0, 0, 1))
    input_tables = bytes(range(256)) * 4
    clut = bytearray()
    for cyan in (0.0, 1.0):
        for magenta in (0.0, 1.0):
            for yellow in (0.0, 1.0):
                for black in (0.0, 1.0):
                    red = (1 - cyan) * (1 - black)
                    green = (1 - magenta) * (1 - black)
                    blue = (1 - yellow) * (1 - black)
                    maximum = max(red, green, blue)
                    minimum = min(red, green, blue)
                    lightness = (maximum + minimum) / 2
                    a = (red - green) * 96
                    b = (green - blue) * 96
                    clut.extend(
                        (
                            round(lightness * 255),
                            round(max(0, min(255, a + 128))),
                            round(max(0, min(255, b + 128))),
                        )
                    )
    output_tables = bytes(range(256)) * 3
    return header + matrix + input_tables + bytes(clut) + output_tables


def synthetic_cmyk_profile() -> bytes:
    """Build a valid ICC v2 CMYK input profile consumed by LittleCMS."""

    tags = {
        b"A2B0": _cmyk_lut_tag(),
        b"cprt": _text_tag("Generated by the IPW Recovery 2E fixture builder"),
        b"desc": _text_tag("IPW synthetic CMYK input"),
        b"wtpt": _xyz_tag(0.9642, 1.0, 0.8249),
    }
    table_size = 4 + len(tags) * 12
    offset = 128 + table_size
    entries = bytearray(struct.pack(">I", len(tags)))
    payload = bytearray()
    for signature, value in sorted(tags.items()):
        padding = (-offset) % 4
        if padding:
            payload.extend(b"\x00" * padding)
            offset += padding
        entries.extend(signature + struct.pack(">II", offset, len(value)))
        payload.extend(value)
        offset += len(value)

    profile_size = 128 + len(entries) + len(payload)
    header = bytearray(128)
    header[0:4] = struct.pack(">I", profile_size)
    header[4:8] = b"pyIP"
    header[8:12] = b"\x02\x10\x00\x00"
    header[12:16] = b"scnr"
    header[16:20] = b"CMYK"
    header[20:24] = b"Lab "
    header[24:36] = struct.pack(">6H", 2026, 9, 4, 0, 0, 0)
    header[36:40] = b"acsp"
    header[40:44] = b"MSFT"
    header[64:68] = struct.pack(">I", 1)
    header[68:80] = _fixed(0.9642) + _fixed(1.0) + _fixed(0.8249)
    header[80:84] = b"IPW2"
    return bytes(header + entries + payload)


def _pattern(width: int, height: int, *, alpha: bool = False) -> Image.Image:
    horizontal = Image.linear_gradient("L").rotate(90, expand=True).resize((width, height))
    vertical = Image.linear_gradient("L").resize((width, height))
    blue = ImageChops.add_modulo(horizontal, vertical)
    image = Image.merge("RGB", (horizontal, vertical, blue))
    draw = ImageDraw.Draw(image)
    step = max(12, min(width, height) // 10)
    for index in range(0, min(width, height), step * 2):
        draw.ellipse(
            (index, index // 2, min(width - 1, index + step), min(height - 1, index + step)),
            fill=(230, 72, 78),
        )
    if not alpha:
        return image
    return Image.merge("RGBA", (*image.split(), horizontal))


def _save(image: Image.Image, format_name: str, **kwargs: object) -> bytes:
    output = io.BytesIO()
    image.save(output, format=format_name, **kwargs)
    return output.getvalue()


def _metadata_exif(thumbnail: bytes) -> bytes:
    description = b"Synthetic metadata fixture\x00"
    software = b"IPW fixture camera\x00"
    captured = b"2026:09:04 08:30:00\x00"
    maker = b"synthetic-private-maker-note"
    rationals = struct.pack("<6I", 12, 1, 34, 1, 56, 1)

    ifd0_offset = 8
    ifd0_size = 2 + 5 * 12 + 4
    ifd1_offset = ifd0_offset + ifd0_size
    ifd1_size = 2 + 2 * 12 + 4
    exif_offset = ifd1_offset + ifd1_size
    exif_size = 2 + 2 * 12 + 4
    gps_offset = exif_offset + exif_size
    gps_size = 2 + 2 * 12 + 4
    variable_offset = gps_offset + gps_size

    description_offset = variable_offset
    software_offset = description_offset + len(description)
    captured_offset = software_offset + len(software)
    maker_offset = captured_offset + len(captured)
    rationals_offset = maker_offset + len(maker)
    thumbnail_offset = rationals_offset + len(rationals)

    def entry(tag: int, value_type: int, count: int, value: int | bytes) -> bytes:
        encoded = value if isinstance(value, bytes) else struct.pack("<I", value)
        return struct.pack("<HHI", tag, value_type, count) + encoded.ljust(4, b"\x00")[:4]

    ifd0 = (
        struct.pack("<H", 5)
        + entry(0x010E, 2, len(description), description_offset)
        + entry(0x0112, 3, 1, struct.pack("<H", 6))
        + entry(0x0131, 2, len(software), software_offset)
        + entry(0x8769, 4, 1, exif_offset)
        + entry(0x8825, 4, 1, gps_offset)
        + struct.pack("<I", ifd1_offset)
    )
    ifd1 = (
        struct.pack("<H", 2)
        + entry(0x0201, 4, 1, thumbnail_offset)
        + entry(0x0202, 4, 1, len(thumbnail))
        + struct.pack("<I", 0)
    )
    exif_ifd = (
        struct.pack("<H", 2)
        + entry(0x9003, 2, len(captured), captured_offset)
        + entry(0x927C, 7, len(maker), maker_offset)
        + struct.pack("<I", 0)
    )
    gps_ifd = (
        struct.pack("<H", 2)
        + entry(1, 2, 2, b"N\x00")
        + entry(2, 5, 3, rationals_offset)
        + struct.pack("<I", 0)
    )
    tiff = (
        b"II\x2a\x00"
        + struct.pack("<I", ifd0_offset)
        + ifd0
        + ifd1
        + exif_ifd
        + gps_ifd
        + description
        + software
        + captured
        + maker
        + rationals
        + thumbnail
    )
    return b"Exif\x00\x00" + tiff


def _segment(marker: int, payload: bytes) -> bytes:
    return bytes((0xFF, marker)) + struct.pack(">H", len(payload) + 2) + payload


def metadata_jpeg() -> bytes:
    thumbnail = _save(_pattern(24, 16), "JPEG", quality=82, optimize=False, progressive=False)
    exif = _metadata_exif(thumbnail)
    base = _save(
        _pattern(320, 200),
        "JPEG",
        quality=88,
        subsampling=0,
        optimize=False,
        progressive=False,
        exif=exif,
    )
    xmp = (
        b"http://ns.adobe.com/xap/1.0/\x00"
        b"<x:xmpmeta xmlns:x='adobe:ns:meta/'><rdf:RDF/></x:xmpmeta>"
    )
    iptc = b"Photoshop 3.0\x00synthetic IPTC fixture"
    comment = b"Synthetic customer comment"
    return (
        base[:2] + _segment(0xE1, xmp) + _segment(0xED, iptc) + _segment(0xFE, comment) + base[2:]
    )


def cmyk_jpeg() -> bytes:
    return _save(
        _pattern(360, 240).convert("CMYK"),
        "JPEG",
        quality=90,
        subsampling=0,
        optimize=False,
        progressive=False,
        icc_profile=synthetic_cmyk_profile(),
    )


def comparison_previews() -> tuple[bytes, bytes]:
    """Build same-geometry visual fixtures for registered preview UI states."""

    original = _pattern(1200, 900)
    contrasted = ImageEnhance.Contrast(original).enhance(1.12)
    curve = [round(255 * ((value / 255) ** 0.94)) for value in range(256)]
    current = contrasted.point(curve * 3)
    return (
        _save(original, "PNG", optimize=False, compress_level=6),
        _save(current, "PNG", optimize=False, compress_level=6),
    )


def fixtures() -> tuple[Fixture, ...]:
    srgb = _canonical_srgb_profile()
    oriented_exif = Image.Exif()
    oriented_exif[274] = 6
    original_preview, current_preview = comparison_previews()
    return (
        Fixture(
            "photographic-640x400.jpg",
            _save(
                _pattern(640, 400),
                "JPEG",
                quality=90,
                subsampling=0,
                optimize=False,
                progressive=False,
            ),
            "synthetic photographic-style RGB JPEG",
        ),
        Fixture(
            "transparent-256x192.png",
            _save(_pattern(256, 192, alpha=True), "PNG", optimize=False, compress_level=6),
            "RGBA PNG with a deterministic alpha ramp",
        ),
        Fixture(
            "source-320x200.webp",
            _save(_pattern(320, 200), "WEBP", quality=86, method=4, exact=True),
            "lossy RGB WebP source",
        ),
        Fixture(
            "source-240x180.tiff",
            _save(_pattern(240, 180), "TIFF", compression="tiff_deflate"),
            "deflate-compressed RGB TIFF source",
        ),
        Fixture(
            "orientation6-160x96.jpg",
            _save(
                _pattern(160, 96),
                "JPEG",
                quality=88,
                optimize=False,
                progressive=False,
                exif=oriented_exif,
            ),
            "JPEG whose EXIF orientation 6 yields a 96 by 160 display image",
        ),
        Fixture(
            "private-metadata-320x200.jpg",
            metadata_jpeg(),
            "JPEG with GPS, XMP, IPTC, comment, maker-note, software and thumbnail metadata",
        ),
        Fixture(
            "tagged-rgb-320x200.png",
            _save(_pattern(320, 200), "PNG", optimize=False, compress_level=6, icc_profile=srgb),
            "RGB PNG tagged with the canonical generated sRGB profile",
        ),
        Fixture(
            "cmyk-360x240.jpg",
            cmyk_jpeg(),
            "CMYK JPEG tagged with the generated test-only CMYK input profile",
        ),
        Fixture(
            "bounded-high-resolution-3200x2600.png",
            _save(_pattern(3200, 2600), "PNG", optimize=False, compress_level=6),
            "8.32 MP RGB PNG above the synchronous preview threshold",
        ),
        Fixture(
            "preview-original-1200x900.png",
            original_preview,
            "same-geometry registered Original preview used only for deterministic "
            "visual presentation",
        ),
        Fixture(
            "preview-current-1200x900.png",
            current_preview,
            "same-geometry registered Current preview with deterministic contrast and "
            "curve corrections",
        ),
    )


def repo_root_from_here() -> Path:
    return Path(__file__).resolve().parents[1]


def manifest_payload(values: tuple[Fixture, ...]) -> bytes:
    payload = {
        "schema_version": "1.0.0",
        "rights": "Generated geometric fixtures; no third-party or customer content.",
        "generator": "tools/make_recovery_2e_fixtures.py",
        "fixtures": [
            {
                "name": value.name,
                "description": value.description,
                "byte_size": len(value.data),
                "sha256": hashlib.sha256(value.data).hexdigest(),
            }
            for value in values
        ],
    }
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode()


def _metadata_value(value: object) -> object:
    if isinstance(value, bytes):
        return {"bytes": len(value), "sha256": hashlib.sha256(value).hexdigest()}
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    if isinstance(value, (list, tuple)):
        return [_metadata_value(item) for item in value]
    return repr(value)


def decoded_signature(payload: bytes) -> dict[str, Any]:
    """Describe decoded behavior without treating compressed bytes as portable."""

    with Image.open(io.BytesIO(payload)) as opened:
        opened.load()
        return {
            "format": opened.format,
            "mode": opened.mode,
            "size": list(opened.size),
            "frames": int(getattr(opened, "n_frames", 1)),
            "pixels_sha256": hashlib.sha256(opened.tobytes()).hexdigest(),
            "metadata": {
                key: _metadata_value(value)
                for key, value in sorted(opened.info.items())
                if key not in {"duration"}
            },
        }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify exact canonical bytes")
    mode.add_argument(
        "--compatibility",
        action="store_true",
        help="verify decoded pixels, dimensions, format and metadata",
    )
    parser.add_argument("--repo-root", type=Path, default=repo_root_from_here())
    args = parser.parse_args(argv)
    directory = args.repo_root / "data" / "fixtures" / "images" / "recovery2e"
    values = fixtures()
    manifest = manifest_payload(values)
    outputs = [*((value.name, value.data) for value in values), ("manifest.json", manifest)]
    if args.compatibility:
        expected_manifest = directory / "manifest.json"
        if not expected_manifest.is_file():
            sys.stderr.write("Recovery 2E generated fixture manifest is missing\n")
            return 1
        committed = json.loads(expected_manifest.read_text(encoding="utf-8"))
        entries = {entry["name"]: entry for entry in committed.get("fixtures", [])}
        problems = 0
        for value in values:
            entry = entries.get(value.name)
            path = directory / value.name
            if not isinstance(entry, dict) or not path.is_file():
                sys.stderr.write(f"Recovery 2E fixture is missing: {value.name}\n")
                problems += 1
                continue
            canonical = path.read_bytes()
            if len(canonical) != entry.get("byte_size") or hashlib.sha256(
                canonical
            ).hexdigest() != entry.get("sha256"):
                sys.stderr.write(f"Recovery 2E fixture integrity failed: {value.name}\n")
                problems += 1
                continue
            if decoded_signature(canonical) != decoded_signature(value.data):
                sys.stderr.write(
                    f"Recovery 2E decoded pixels, dimensions, format or metadata drifted: "
                    f"{value.name}\n"
                )
                problems += 1
            else:
                sys.stdout.write(f"{value.name:<48} decoded compatibility PASS\n")
        if set(entries) != {value.name for value in values}:
            sys.stderr.write("Recovery 2E fixture inventory differs from the canonical manifest\n")
            problems += 1
        return 1 if problems else 0

    if args.check:
        expected_manifest = directory / "manifest.json"
        if not expected_manifest.is_file() or expected_manifest.read_bytes() != manifest:
            sys.stderr.write("Recovery 2E generated fixture manifest has drifted\n")
            return 1
        for name, data in outputs:
            path = directory / name
            if not path.is_file() or path.read_bytes() != data:
                sys.stderr.write(f"Recovery 2E generated fixture has drifted: {name}\n")
                return 1
        for value in values:
            with Image.open(io.BytesIO(value.data)) as opened:
                opened.verify()
            sys.stdout.write(
                f"{value.name:<48} reproducible  {len(value.data):>9} B  "
                f"{hashlib.sha256(value.data).hexdigest()[:16]}\n"
            )
        return 0

    directory.mkdir(parents=True, exist_ok=True)
    for name, data in outputs:
        path = directory / name
        path.write_bytes(data)
        sys.stdout.write(
            f"wrote {name:<48} {len(data):>9} B  sha256={hashlib.sha256(data).hexdigest()}\n"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
