"""Deterministic fixture generator.

Provenance for the committed fixtures: they are generated by this script, in this
repository, from a pure function of pixel coordinates. No third-party rights, no
people, no sensitive content - trivially rights-cleared, which is exactly what
AGENTS.md asks of anything that enters Git.

Why the PNG is written by hand
------------------------------
POC-001 must produce **byte-identical** output on any machine. ``zlib.compress``
does not guarantee that: its output can differ between zlib versions and builds.
So the encoder below emits DEFLATE **stored** (uncompressed) blocks, whose byte
layout is fixed by RFC 1951 and cannot vary. ``zlib`` is still used, but only for
``crc32`` and ``adler32``, which are checksums with exactly one correct answer.

The result is a slightly larger file (about 12 KB for 64x64 RGB) that is
reproducible forever, on any platform, with no imaging dependency at all - so no
Pillow, no OpenCV and no licence entry enters the project before POC-003 needs
one.

Usage::

    python tools/make_fixtures.py            # write fixtures
    python tools/make_fixtures.py --check    # verify reproducibility
"""

from __future__ import annotations

import argparse
import hashlib
import struct
import sys
import zlib
from pathlib import Path

PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
FIXTURE_NAME = "synthetic-gradient-64.png"
WIDTH = 64
HEIGHT = 64


def _chunk(tag: bytes, payload: bytes) -> bytes:
    """One PNG chunk: length, type, data, CRC-32 of type+data."""
    return (
        struct.pack(">I", len(payload))
        + tag
        + payload
        + struct.pack(">I", zlib.crc32(tag + payload) & 0xFFFFFFFF)
    )


def _stored_deflate(data: bytes) -> bytes:
    """Wrap ``data`` in a zlib stream built only from DEFLATE stored blocks.

    Header ``78 01`` is CM=8, CINFO=7, FLEVEL=0 with a valid FCHECK
    (0x7801 = 30721, divisible by 31). Each stored block is a byte-aligned
    header, then LEN and its one's complement, then the raw bytes.
    """
    out = bytearray(b"\x78\x01")
    max_block = 0xFFFF
    if not data:
        out += b"\x01" + struct.pack("<HH", 0, 0xFFFF)
    else:
        for offset in range(0, len(data), max_block):
            block = data[offset : offset + max_block]
            final = offset + max_block >= len(data)
            out.append(0x01 if final else 0x00)
            out += struct.pack("<HH", len(block), len(block) ^ 0xFFFF)
            out += block
    out += struct.pack(">I", zlib.adler32(data) & 0xFFFFFFFF)
    return bytes(out)


def _pixel(x: int, y: int) -> tuple[int, int, int]:
    """A pure function of position: gradient plus an 8-pixel checkerboard.

    The checkerboard gives sharp edges (useful for later sharpening and tiling
    tests) and the gradient gives smooth tone (useful for banding and colour
    tests), in one tiny image.
    """
    red = (x * 4) % 256
    green = (y * 4) % 256
    blue = 255 if ((x // 8) + (y // 8)) % 2 == 0 else 32
    return red, green, blue


def render_png(width: int = WIDTH, height: int = HEIGHT) -> bytes:
    """Render the fixture as 8-bit RGB PNG bytes."""
    raw = bytearray()
    for y in range(height):
        raw.append(0)  # filter type 0 (None), so the scanline is stored verbatim
        for x in range(width):
            raw.extend(_pixel(x, y))

    ihdr = struct.pack(
        ">IIBBBBB",
        width,
        height,
        8,  # bit depth
        2,  # colour type 2 = truecolour RGB
        0,  # deflate
        0,  # adaptive filtering
        0,  # no interlace
    )
    return (
        PNG_MAGIC
        + _chunk(b"IHDR", ihdr)
        + _chunk(b"IDAT", _stored_deflate(bytes(raw)))
        + _chunk(b"IEND", b"")
    )


NOISE_NAME = "synthetic-noise-64.png"
ALPHA_NAME = "synthetic-alpha-32.png"


def _noise(x: int, y: int, channel: int) -> int:
    """Deterministic pseudo-random noise in [-40, 40].

    A fixed integer hash rather than ``random``: the lint rules ban ambient
    randomness precisely so fixtures stay byte-reproducible, and a seeded PRNG
    would still depend on the implementation of the generator.
    """
    h = (x * 374761393 + y * 668265263 + channel * 2246822519 + 3266489917) & 0xFFFFFFFF
    h = (h ^ (h >> 13)) * 1274126177 & 0xFFFFFFFF
    h = h ^ (h >> 16)
    return (h % 81) - 40


def render_noise_png(width: int = 64, height: int = 64) -> bytes:
    """A smooth gradient carrying additive noise.

    Denoise and sharpen goldens need an image with genuine high-frequency
    content. The plain gradient fixture has none: a 3x3 median filter of a linear
    ramp returns the centre value unchanged, so a denoise golden taken from it is
    byte-identical to a plain re-encode and proves nothing. This fixture gives the
    filter both something to remove (the noise) and something it must preserve
    (the underlying gradient).
    """
    raw = bytearray()
    for y in range(height):
        raw.append(0)
        for x in range(width):
            base = (
                (x * 255) // max(width - 1, 1),
                (y * 255) // max(height - 1, 1),
                128,
            )
            for channel, value in enumerate(base):
                raw.append(min(255, max(0, value + _noise(x, y, channel))))

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (
        PNG_MAGIC
        + _chunk(b"IHDR", ihdr)
        + _chunk(b"IDAT", _stored_deflate(bytes(raw)))
        + _chunk(b"IEND", b"")
    )


def render_alpha_png(size: int = 32) -> bytes:
    """RGBA with a genuine alpha ramp reaching full transparency.

    Transparency behaviour is an explicit POC-004 acceptance criterion and cannot
    be tested against an opaque fixture. Alpha varies across the image and reaches
    zero, so flattening onto a background is visible, and converting to a format
    without alpha is a real loss that must be declared rather than silently
    performed (USER_FLOWS section 5).
    """
    raw = bytearray()
    span = max(2 * (size - 1), 1)
    for y in range(size):
        raw.append(0)
        for x in range(size):
            alpha = max(0, min(255, (x + y) * 255 // span))
            raw += bytes(
                (
                    (x * 255) // max(size - 1, 1),
                    (y * 255) // max(size - 1, 1),
                    160,
                    alpha,
                )
            )

    ihdr = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)  # colour type 6 = RGBA
    return (
        PNG_MAGIC
        + _chunk(b"IHDR", ihdr)
        + _chunk(b"IDAT", _stored_deflate(bytes(raw)))
        + _chunk(b"IEND", b"")
    )


def fixture_path(repo_root: Path) -> Path:
    return repo_root / "data" / "fixtures" / "images" / FIXTURE_NAME


def noise_path(repo_root: Path) -> Path:
    return repo_root / "data" / "fixtures" / "images" / NOISE_NAME


def alpha_path(repo_root: Path) -> Path:
    return repo_root / "data" / "fixtures" / "images" / ALPHA_NAME


def repo_root_from_here() -> Path:
    # tools/make_fixtures.py -> repository root
    return Path(__file__).resolve().parents[1]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the committed benchmark fixtures.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed fixture matches freshly rendered bytes, without writing",
    )
    parser.add_argument("--repo-root", type=Path, default=repo_root_from_here())
    args = parser.parse_args(argv)

    outputs = [
        (fixture_path(args.repo_root), render_png(), f"{WIDTH}x{HEIGHT} RGB 8-bit"),
        (noise_path(args.repo_root), render_noise_png(), "64x64 RGB 8-bit, gradient + noise"),
        (alpha_path(args.repo_root), render_alpha_png(), "32x32 RGBA 8-bit, alpha ramp"),
    ]
    if args.check:
        failures = 0
        for path, payload, _ in outputs:
            if not path.is_file():
                sys.stderr.write(f"fixture missing: {path.name}\n")
                failures += 1
            elif path.read_bytes() != payload:
                sys.stderr.write(f"not reproducible: {path.name}\n")
                failures += 1
            else:
                sys.stdout.write(
                    f"{path.name:<30} reproducible  {len(payload):>6} B  "
                    f"{hashlib.sha256(payload).hexdigest()[:16]}\n"
                )
        return 1 if failures else 0

    for path, payload, description in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
        sys.stdout.write(
            f"wrote {path.name:<30} {len(payload):>6} B  "
            f"sha256={hashlib.sha256(payload).hexdigest()}\n"
        )
        sys.stdout.write(f"      {description}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
