"""Versioned benchmark contract for the Image & PDF Workspace POC.

This package is the single source of truth for every document the benchmark
foundation reads or writes. It is deliberately independent of the benchmark
runner so that other consumers - notably the POC-005 browser lab, which is
TypeScript - can validate against the exported JSON Schema in ``packages/schemas/v1/``
without depending on the runner.

The nine schema families required by POC-001:

============================  ========================================
Asset manifest entry          :mod:`ipw.contracts.asset`
Operation / settings          :mod:`ipw.contracts.operation`
Processor identity            :mod:`ipw.contracts.processor`
Licence disposition           :mod:`ipw.contracts.licence`
Safety inspection result      :mod:`ipw.contracts.safety`
Benchmark run                 :mod:`ipw.contracts.run`
Per-asset result              :mod:`ipw.contracts.result`
Timing / memory / cost        :mod:`ipw.contracts.measurement`
Normalised failure            :mod:`ipw.contracts.failure`
============================  ========================================
"""

from __future__ import annotations

from ipw.contracts.asset import (
    AssetCategory,
    AssetManifestEntry,
    DegradationRecipe,
    ExternalRef,
    GroundTruthRelationship,
    MediaType,
    Provenance,
)
from ipw.contracts.common import ContractModel
from ipw.contracts.environment import EnvironmentRecord, HardwareRecord
from ipw.contracts.failure import (
    FailureCategory,
    FailureCode,
    NextAction,
    NormalizedFailure,
    Severity,
    failure,
)
from ipw.contracts.licence import (
    COMMERCIAL_PURPOSES,
    ComponentKind,
    Disposition,
    LicenceDisposition,
    RunPurpose,
    WeightFormat,
    is_permitted,
    least_permissive,
)
from ipw.contracts.manifest import AssetManifest
from ipw.contracts.measurement import (
    CostBreakdown,
    Estimate,
    Measurement,
    MemoryUsage,
    ThermalState,
    Timing,
)
from ipw.contracts.operation import (
    AnySettings,
    Operation,
    OperationFamily,
    OperationKind,
    ProcessingRoute,
    ProcessingVariant,
)
from ipw.contracts.processor import (
    OutputArtifact,
    Processor,
    ProcessorIdentity,
    ProcessOutcome,
    RuntimeIdentity,
    Support,
    WeightsIdentity,
)
from ipw.contracts.product import (
    AssetOriginal,
    DocumentVersion,
    ExportRequest,
    ExportResult,
    ExportState,
    JobCheckpoint,
    JobKind,
    JobState,
    LicenceReleaseGate,
    ProcessingJob,
    ProcessorFacts,
    ProductContractModel,
    ProductError,
    Project,
    ProjectNodeKind,
    ProvenanceRecord,
    SourceVersion,
    StorageObjectRef,
    TraceContext,
    WorkspaceReference,
)
from ipw.contracts.product_kernel import (
    Actor,
    AssetOriginalRecord,
    AuditEvent,
    AuditEventList,
    Collection,
    CollectionProjectRelation,
    DefaultFilesLocation,
    EffectivePermission,
    ErrorDetail,
    ErrorEnvelope,
    FileList,
    FileLocationKind,
    FileLocationRef,
    FileReferenceOwnerKind,
    GuestSessionAuthorization,
    GuestSessionRecord,
    IdempotentCommandResult,
    IdentityProviderKind,
    IdentityReference,
    IntakeFailure,
    JobEventList,
    JobEventRecord,
    MalwareScanState,
    Membership,
    ObjectReference,
    Permission,
    PermissionGrant,
    PermissionOrigin,
    ProcessingJobKind,
    ProcessingJobRecord,
    ProcessingJobState,
    ProductKernelContractModel,
    ProjectList,
    ProjectRecord,
    ReusableFileReference,
    RolePreset,
    SourceFacts,
    SourceVersionRecord,
    UploadAuthorization,
    UploadConstraints,
    UploadOwnerKind,
    UploadSessionCreated,
    UploadSessionRecord,
    UploadSessionState,
    UploadTransferKind,
    UsageAdminDimensions,
    UsageEvent,
    UsageSummary,
    WorkspaceContext,
    WorkspaceFile,
    WorkspaceList,
    WorkspaceProjectPolicy,
)
from ipw.contracts.product_kernel import (
    Workspace as ProductWorkspace,
)
from ipw.contracts.report import (
    AssetInventory,
    BenchmarkReport,
    GroundTruthSummary,
    ReportIdentity,
    RightsSummary,
    RunReference,
)
from ipw.contracts.result import AssetResult, LedgerEntry, ResultIdentity, ResultState
from ipw.contracts.run import BenchmarkRun, RunIdentity, RunSummary
from ipw.contracts.runtime import (
    CancellationToken,
    Clock,
    FixedClock,
    InputRef,
    OriginalMutatedError,
    ProcessingCancelledError,
    RunContext,
    SystemClock,
    Workspace,
)
from ipw.contracts.safety import (
    DEFAULT_SAFETY_POLICY,
    HandlingClass,
    InspectionResult,
    Orientation,
    RiskFlag,
    SafetyPolicy,
)
from ipw.contracts.version import (
    PRODUCT_SCHEMA_MAJOR,
    PRODUCT_SCHEMA_VERSION,
    SCHEMA_MAJOR,
    SCHEMA_VERSION,
)

__all__ = [
    "COMMERCIAL_PURPOSES",
    "DEFAULT_SAFETY_POLICY",
    "PRODUCT_SCHEMA_MAJOR",
    "PRODUCT_SCHEMA_VERSION",
    "SCHEMA_MAJOR",
    "SCHEMA_VERSION",
    "Actor",
    "AnySettings",
    "AssetCategory",
    "AssetInventory",
    "AssetManifest",
    "AssetManifestEntry",
    "AssetOriginal",
    "AssetOriginalRecord",
    "AssetResult",
    "AuditEvent",
    "AuditEventList",
    "BenchmarkReport",
    "BenchmarkRun",
    "CancellationToken",
    "Clock",
    "Collection",
    "CollectionProjectRelation",
    "ComponentKind",
    "ContractModel",
    "CostBreakdown",
    "DefaultFilesLocation",
    "DegradationRecipe",
    "Disposition",
    "DocumentVersion",
    "EffectivePermission",
    "EnvironmentRecord",
    "ErrorDetail",
    "ErrorEnvelope",
    "Estimate",
    "ExportRequest",
    "ExportResult",
    "ExportState",
    "ExternalRef",
    "FailureCategory",
    "FailureCode",
    "FileList",
    "FileLocationKind",
    "FileLocationRef",
    "FileReferenceOwnerKind",
    "FixedClock",
    "GroundTruthRelationship",
    "GroundTruthSummary",
    "GuestSessionAuthorization",
    "GuestSessionRecord",
    "HandlingClass",
    "HardwareRecord",
    "IdempotentCommandResult",
    "IdentityProviderKind",
    "IdentityReference",
    "InputRef",
    "InspectionResult",
    "IntakeFailure",
    "JobCheckpoint",
    "JobEventList",
    "JobEventRecord",
    "JobKind",
    "JobState",
    "LedgerEntry",
    "LicenceDisposition",
    "LicenceReleaseGate",
    "MalwareScanState",
    "Measurement",
    "MediaType",
    "Membership",
    "MemoryUsage",
    "NextAction",
    "NormalizedFailure",
    "ObjectReference",
    "Operation",
    "OperationFamily",
    "OperationKind",
    "Orientation",
    "OriginalMutatedError",
    "OutputArtifact",
    "Permission",
    "PermissionGrant",
    "PermissionOrigin",
    "ProcessOutcome",
    "ProcessingCancelledError",
    "ProcessingJob",
    "ProcessingJobKind",
    "ProcessingJobRecord",
    "ProcessingJobState",
    "ProcessingRoute",
    "ProcessingVariant",
    "Processor",
    "ProcessorFacts",
    "ProcessorIdentity",
    "ProductContractModel",
    "ProductError",
    "ProductKernelContractModel",
    "ProductWorkspace",
    "Project",
    "ProjectList",
    "ProjectNodeKind",
    "ProjectRecord",
    "Provenance",
    "ProvenanceRecord",
    "ReportIdentity",
    "ResultIdentity",
    "ResultState",
    "ReusableFileReference",
    "RightsSummary",
    "RiskFlag",
    "RolePreset",
    "RunContext",
    "RunIdentity",
    "RunPurpose",
    "RunReference",
    "RunSummary",
    "RuntimeIdentity",
    "SafetyPolicy",
    "Severity",
    "SourceFacts",
    "SourceVersion",
    "SourceVersionRecord",
    "StorageObjectRef",
    "Support",
    "SystemClock",
    "ThermalState",
    "Timing",
    "TraceContext",
    "UploadAuthorization",
    "UploadConstraints",
    "UploadOwnerKind",
    "UploadSessionCreated",
    "UploadSessionRecord",
    "UploadSessionState",
    "UploadTransferKind",
    "UsageAdminDimensions",
    "UsageEvent",
    "UsageSummary",
    "WeightFormat",
    "WeightsIdentity",
    "Workspace",
    "WorkspaceContext",
    "WorkspaceFile",
    "WorkspaceList",
    "WorkspaceProjectPolicy",
    "WorkspaceReference",
    "failure",
    "is_permitted",
    "least_permissive",
]
